Repository Dream-Transcendence/ft_transcendence, pull requests merged in 2022-10, with the labels that each got.

#116 ✨ feat(server): Users API 기본 로직 구현
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/game/game.dto.ts
  packages/server/src/main.ts
  packages/server/src/users/dto/auth-user.dto.ts
  packages/server/src/users/dto/create-user.dto.ts
  packages/server/src/users/dto/patch-user.dto.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.entity.ts
  packages/server/src/users/users.module.ts
  packages/server/src/users/users.providers.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, back-end, design

#118 ✨ feat(client): change form of custom button
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/icon/CustomIconButtion.tsx
  packages/client/src/atoms/button/linkPage/LinkPageIconButton.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/molecules/ChatSection/ChatInput.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/molecules/ChatSection/RoomInfoChatRoomBoxFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoDMBoxFunction.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/molecules/ProfileSection/UserInviteBox.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/PingpongLayout.tsx
  packages/client/src/types/Link.type.ts
Labels: front-end

#121 🐛 fix(server): room 로직 수정 (#92)
  node_modules/.yarn-integrity
  packages/server/src/chats/dto/room.dto.ts
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.entity.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/users/dto/user.dto.ts
Labels: enhancement, back-end

#123 Feat/117/chat status structure
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/PingpongLayout.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
Labels: front-end

#125 ✨ feat(server): Build Docker Env
  .env
  .gitignore
  Dockerfile
  docker-compose.yml
  packages/server/src/database/database.providers.ts
  packages/server/src/main.ts
Labels: enhancement, back-end

#126 ✨ feat(server): Add pgAdmin4 container on Docker
  .env
  Dockerfile
  docker-compose.yml
  node_modules/.yarn-integrity
  package-lock.json
  packages/server/package.json
Labels: enhancement, back-end

#127 Feat/124/set chat axios data
  docker-compose.yml
  node_modules/.yarn-integrity
  packages/client/package.json
  packages/client/src/atoms/button/linkPage/LinkPageTextButton.tsx
  packages/client/src/atoms/input/passwordBox.tsx
  packages/client/src/atoms/list/styles/ListStylesCSS.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/configs/RoomType.ts
  packages/client/src/molecules/ChatPopUp/SetChatRoomPassword.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/template/ChatMainSection/ChatRoomListTemplate.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/types/Link.type.ts
  yarn.lock
Labels: bug, enhancement, front-end

#137 ✨ feat(server): connect local server srcs to Docker volume (#136)
  Dockerfile
  docker-compose.yml
Labels: back-end

#138 Feat/129/create enterd chat infobox
  docker-compose.yml
  packages/client/src/atoms/input/passwordBox.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/ChatSection/RoomElementTitle.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/molecules/ChatSection/RoomInfoDMBoxFunction.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/organisms/ChatMainSection/EnteredDMInfo.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/template/ChatMainSection/EnteredDMTemplate.tsx
  packages/client/src/types/Room.type.ts
Labels: enhancement, front-end

#143 🐛 fix(server): getChannel, enterChannel, patchRoomInfo 로직 수정 (#142)
  docker-compose.yml
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.service.ts
Labels: enhancement, back-end

#148 채팅방 참여인원 컴포넌트
  packages/client/src/index.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/types/Participant.type.ts
  packages/client/src/types/Room.type.ts
Labels: enhancement, front-end

#146 ✨ feat(server): implement unblockUser() & add request/response body examples for Swagger
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/game/game.dto.ts
  packages/server/src/users/dto/create-user.dto.ts
  packages/server/src/users/dto/patch-user.dto.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, back-end

#154 ✨ feat(server): add .sql file to initialize data in database (#150)
  Dockerfile.database
  docker-compose.yml
  packages/server/init/init.sql
  packages/server/src/database/database.providers.ts
Labels: enhancement, back-end

#151 ✨ feat(client/creatroom): create room except inviting
  packages/client/src/atoms/input/passwordBox.tsx
  packages/client/src/atoms/radio/RadioGroupButton.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomInvite.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomName.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomPassword.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomType.tsx
  packages/client/src/molecules/ChatSidebar/CreateChatRoom.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/types/Room.type.ts
Labels: enhancement, front-end

#156 Feat/128/apply userdata
  .env
  .gitignore
  Dockerfile
  node_modules/.yarn-integrity
  package-lock.json
  package.json
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/atoms/button/icon/FileUploadBotton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageComponentButton.tsx
  packages/client/src/atoms/button/switch/SecondAuth.tsx
  packages/client/src/atoms/input/passwordBox.tsx
  packages/client/src/atoms/profile/AvartarStyles/AvartarStyleCss.tsx
  packages/client/src/atoms/profile/NavProfile.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/atoms/profile/ProfileImage.tsx
  packages/client/src/atoms/text/GamePlayer.tsx
  packages/client/src/atoms/text/MatchType.tsx
  packages/client/src/atoms/text/NicknameInitTextField.tsx
  packages/client/src/atoms/text/OtherProfileNicname.tsx
  packages/client/src/atoms/text/ProfileNickname.tsx
  packages/client/src/atoms/text/ProfileUserStatLadder.tsx
  packages/client/src/atoms/text/ProfileUserStatLose.tsx
  packages/client/src/atoms/text/ProfileUserStatWin.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/configs/Spot.string.ts
  packages/client/src/index.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/GameSecton/GameResultMadal.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/molecules/ProfileSection/StatResult.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/molecules/ProfileSection/UserInviteBox.tsx
  packages/client/src/molecules/ProfileSection/UserProfileBox.tsx
  packages/client/src/molecules/ProfileSection/UserProfileBoxWithCircle.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/OtherProfilePage.tsx
  packages/client/src/pages/PingpongLayout.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/pages/ProfilePage.tsx
  packages/client/src/template/ProfileSection/OtherProfileTemplate.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
  packages/client/src/types/Link.type.ts
  packages/client/src/types/Profile.type.ts
  yarn.lock
Labels: enhancement, front-end

#158 Feat/109/socket chat
  Dockerfile
  docker-compose.yml
  node_modules/.yarn-integrity
  node_modules/client
  package.json
  packages/client/src/atoms/Image/Image.tsx
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/icon/CustomBoxButton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageComponentButton.tsx
  packages/client/src/atoms/profile/AvartarStyles/AvartarStyleCss.tsx
  packages/client/src/atoms/profile/NavProfile.tsx
  packages/client/src/atoms/text/ProfileUserStatLadder.tsx
  packages/client/src/atoms/text/ProfileUserStatLose.tsx
  packages/client/src/atoms/text/ProfileUserStatWin.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/CommonSection/SendMessageAlert.tsx
  packages/client/src/molecules/GameSecton/GameOption.tsx
  packages/client/src/organisms/GameCreateSection/GameCreateMainSection.tsx
  packages/client/src/organisms/GameCreateSection/GameMap.tsx
  packages/client/src/organisms/GameCreateSection/GameOption.tsx
  packages/client/src/organisms/NicknameInit/NicknameInit.tsx
  packages/client/src/organisms/OrganismsStyles/ProfileOrganismsCss.tsx
  packages/client/src/pages/PageStyles/ProfilePageCss.tsx
  packages/server/package.json
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.entity.ts
  packages/server/src/chats/rooms.gateway.ts
  packages/server/src/chats/rooms.module.ts
  packages/server/src/chats/rooms.providers.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/main.ts
  packages/server/src/users/dto/connect-user.dto.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.entity.ts
  packages/server/src/users/users.module.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: back-end

#163 🐛 fix(server): searchFriend API bug & getRooms dmList to get name and image
  packages/server/src/users/users.service.ts
Labels: bug, back-end

#169 🐛 fix(server): emit just to friends when logOn/Off (#168)
  packages/server/src/users/user.gateway.ts
Labels: back-end

#175 🐛 fix(server): set maxId + 1 for every PK columns (#168)
  packages/server/src/chats/rooms.entity.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/users/users.entity.ts
  packages/server/src/users/users.service.ts
Labels: bug, back-end

#177 Feat/167/set 백엔드에서 만들어준 소켓 api구조를 만들고, 일부 api 적용 작업을 하였습니다.
  node_modules/.yarn-integrity
  packages/client/package.json
  packages/client/src/atoms/input/passwordBox.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedChatRoomList.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/socket/event.ts
  packages/client/src/socket/useSocket.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/server/src/chats/rooms.gateway.ts
  packages/server/src/main.ts
  yarn.lock
Labels: enhancement, front-end

#182 Feat/157/invisible add friend button
  packages/client/src/atoms/button/icon/CustomBoxButton.tsx
  packages/client/src/atoms/button/icon/FileUploadBotton.tsx
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/atoms/profile/ProfileImage.tsx
  packages/client/src/atoms/text/ProfileNickname.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/GameSecton/GameResultMadal.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/organisms/OrganismsStyles/ProfileOrganismsCss.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/PingpongLayout.tsx
  packages/client/src/types/Link.type.ts
  packages/server/init/init.sql
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/users/dto/create-user.dto.ts
  packages/server/src/users/dto/patch-user.dto.ts
  packages/server/src/users/dto/user.dto.ts
Labels: enhancement, front-end

#186 🐛 fix(server/chat): 불필요한 함수 삭제, return값 변경, controller 순서 변경 (#184)
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.gateway.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/main.ts
Labels: back-end

#188 유저 채널 가져오기 API dmList blocked 프로퍼티 추가 & enterChannel PK conflict 해결
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#189 Feat/178/(set) chatting 관련하여 optimistic UI 적용시켜주기
  node_modules/.yarn-integrity
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/configs/Block.case.ts
  packages/client/src/configs/Status.case.ts
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/recoil/chat.recoil.ts
  packages/client/src/socket/event.ts
  packages/client/src/socket/useSocket.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/types/Participant.type.ts
  packages/client/src/types/Room.type.ts
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.service.ts
Labels: enhancement, front-end

#192 Feat/179/implement ping pong
  node_modules/.yarn-integrity
  package.json
  packages/server/src/app.module.ts
  packages/server/src/game/game.controller.ts
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.module.ts
  packages/server/src/game/game.service.ts
  yarn.lock
Labels: enhancement, back-end

#193 Feat/181/search user
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/atoms/input/SearchBox.tsx
  packages/client/src/index.tsx
  packages/client/src/molecules/GameSecton/GameResultMadal.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
  packages/client/src/types/search.type.ts
Labels: enhancement, front-end

#194 Feat/191/get chat history 채팅 히스토리를 불러오는 로직과, 채팅 ui를 수정하였습니다.
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/atoms/list/styles/ListStylesCSS.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/atoms/textPrompt/MessageBox.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/types/Message.type.ts
  packages/server/init/init.sql
Labels: enhancement, front-end

#198 🐛 fix(server/game): 레더 매칭 로직 수정 (#179)
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.service.ts
Labels: enhancement, back-end

#199 Feat/152/adapt search box 채팅방 및 DM을 생성하는 컴포넌트기능 구현
  package-lock.json
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/input/SearchBox.tsx
  packages/client/src/atoms/textPrompt/MessageBox.tsx
  packages/client/src/hooks/useSearch.ts
  packages/client/src/molecules/ChatPopUp/SetChatRoomInvite.tsx
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/ChatSidebar/CreateChatRoom.tsx
  packages/client/src/molecules/ChatSidebar/SearchBox.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/recoil/chat.recoil.ts
  packages/client/src/types/Room.type.ts
  packages/client/src/types/search.type.ts
  packages/server/package.json
  yarn.lock
Labels: enhancement, front-end

#202 Feat/create add friend button
  node_modules/.yarn-integrity
  packages/client/src/App.tsx
  packages/client/src/assets/pong.png
  packages/client/src/atoms/Image/Image.tsx
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/input/SearchBox.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/hooks/useSearch.ts
  packages/client/src/index.tsx
  packages/client/src/molecules/GameSecton/GameOption.tsx
  packages/client/src/organisms/GameCreateSection/GameMap.tsx
  packages/client/src/organisms/OrganismsStyles/ProfileOrganismsCss.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/pages/GameLodingPage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/game.recoil.ts
  packages/client/src/socket/event.ts
  packages/client/src/socket/useSocket.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/types/Game.type.ts
  packages/client/src/types/search.type.ts
Labels: enhancement, front-end

#203 ✨ feat(server): implement Custom game invitation & matching logic (#195)
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, back-end

#208 ✨ feat(server/chat): infinity scroll을 위해 getMessages 로직 수정 (#207)
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.service.ts
Labels: enhancement, back-end

#210 ✨ feat(server): devide user status onGame or not & LogOn/Off sockets emit to all users
  packages/server/init/init.sql
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.module.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/dto/connect-user.dto.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.module.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#211 ✨ feat(server/auth): authGuard처리,jwt token 발급, front에 전달 (#190)
  node_modules/.yarn-integrity
  package-lock.json
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/bakingkim.strategy.ts
  packages/server/src/auth/constants.ts
  packages/server/src/auth/jwt.strategy.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.module.ts
  packages/server/src/main.ts
  packages/server/src/users/dto/create-user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: enhancement, back-end

#213 🐛 fix(server/user): user.gateway 로직 이동(user.service) 및 친구 요청 로직 변경(api to socket)
  package-lock.json
  packages/server/src/game/game.module.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.module.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: back-end

#218 ✨ feat(server): cookie를 설정, request이 왔을 때 cookie 추출해서 userinfo return하는 api추가 (#217)
  node_modules/.yarn-integrity
  package-lock.json
  packages/server/package.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/bakingkim.strategy.ts
  packages/server/src/auth/jwt.strategy.ts
  packages/server/src/main.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: enhancement, back-end

#214 Feat/212/login component 프론트 로그인 작업완료
  packages/client/src/atoms/button/block/NicknameConfirmButton.tsx
  packages/client/src/atoms/text/NicknameInitTextField.tsx
  packages/client/src/atoms/textPrompt/MessageBox.tsx
  packages/client/src/index.tsx
  packages/client/src/molecules/ChatSection/ChatInput.tsx
  packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/organisms/NicknameInit/NicknameInit.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/types/Message.type.ts
  packages/client/src/types/Profile.type.ts
Labels: enhancement, front-end

#223 Fix/216/check chat component after login
  node_modules/.yarn-integrity
  packages/client/package.json
  packages/client/src/App.tsx
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/atoms/button/block/NicknameConfirmButton.tsx
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/atoms/profile/NavProfile.tsx
  packages/client/src/atoms/textPrompt/MessageBox.tsx
  packages/client/src/hooks/useSearch.ts
  packages/client/src/molecules/ChatPopUp/SetChatRoomInvite.tsx
  packages/client/src/molecules/ChatSection/ChatInput.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/ChatSidebar/CreateChatRoom.tsx
  packages/client/src/molecules/ChatSidebar/SearchBox.tsx
  packages/client/src/molecules/GameSecton/GameResultMadal.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedChatRoomList.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/GameLodingPage.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/user.recoil.ts
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
  packages/client/src/types/Message.type.ts
  packages/server/src/auth/jwt.strategy.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/main.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, front-end

#225 ✨ feat(server/user): 유저 프로필 이미지 AWS S3 업로드 로직 추가
  package-lock.json
  packages/server/.gitignore
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/users/dto/patch-user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: enhancement, back-end

#228 ✨ feat(server/user): 유저 2차(이메일) 인증 구현
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, back-end

#232 🐛 fix(server/user): protect UserService handleDisconnect Crash (#231)
  packages/server/src/users/users.service.ts
Labels: bug, back-end

#234 🐛 fix(server): 민감한 정보들 env 처리
  node_modules/.yarn-integrity
  package-lock.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/auth/bakingkim.strategy.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: back-end

#237 🐛 fix(server/user): change searchFriend API implementation pos & add …
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#236 Feat/226/request game
  node_modules/.yarn-integrity
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/block/NicknameConfirmButton.tsx
  packages/client/src/atoms/button/icon/FileUploadBotton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageComponentButton.tsx
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/atoms/list/styles/ListStylesCSS.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/atoms/text/GamePlayer.tsx
  packages/client/src/atoms/text/MatchType.tsx
  packages/client/src/configs/Game.type.ts
  packages/client/src/hooks/useSearch.ts
  packages/client/src/index.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/molecules/ProfileSection/UserInviteBox.tsx
  packages/client/src/organisms/ChatSidebar/JoinedChatRoomList.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/OrganismsStyles/ProfileOrganismsCss.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/pages/GameCreatePage.tsx
  packages/client/src/pages/GameLodingPage.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/PageStyles/ProfilePageCss.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/game.recoil.ts
  packages/client/src/recoil/log.recoil.ts
  packages/client/src/recoil/user.recoil.ts
  packages/client/src/socket/useSocket.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
  packages/client/src/types/Game.type.ts
  packages/client/src/types/Link.type.ts
  packages/client/src/types/LogOn.type.ts
  packages/client/src/types/Profile.type.ts
  packages/client/tsconfig.json
  packages/server/src/users/users.controller.ts
Labels: front-end

#239 🐛 fix(server/user): hotfix crash on getFriend when the user is not a …
  packages/server/src/users/users.service.ts
Labels: bug, back-end

#241 🐛 fix(server): edit enterChannel, deleteChannelParticipant emit message
  packages/server/src/chats/rooms.service.ts
Labels: back-end

#243 ✨ feat(server/user): block duplcate login (#242)
  packages/server/src/users/users.service.ts
Labels: back-end

#244 Feat/204/check logon realtime
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/log.recoil.ts
  packages/client/src/recoil/user.recoil.ts
  packages/client/src/types/LogOn.type.ts
Labels: enhancement, front-end

#248 ✨ feat(server/user): 2nd-auth login & 🔥 ladder match crash hotfix
  packages/server/src/users/dto/auth-user.dto.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: bug, enhancement, back-end

#255 ✨ feat(server/user): add changeUserStatus emits (#254)
  packages/server/src/game/game.service.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#256 Feat/204/check logon realtime
  .env
  .gitignore
  Dockerfile
  docker-compose.yml
  node_modules/.yarn-integrity
  packages/client/src/App.tsx
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/list/styles/ListStylesCSS.tsx
  packages/client/src/atoms/text/GamePlayer.tsx
  packages/client/src/atoms/text/MatchType.tsx
  packages/client/src/configs/Game.type.ts
  packages/client/src/configs/Link.url.ts
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/pages/GameRoutePage.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/pages/SecondOauthPage.tsx
  packages/client/src/socket/event.ts
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/server/src/users/users.service.ts
Labels: enhancement, front-end

#252 ✨ feat(server/game): save game result in db, create rank entity (#221)
  packages/server/init/init.sql
  packages/server/src/auth/jwt.strategy.ts
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/users.entity.ts
  packages/server/src/users/users.providers.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, back-end

#258 ✨ feat(server/game): implement game customization option (#257)
  Dockerfile
  docker-compose.yml
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
Labels: enhancement, back-end

#263 Feat/253/create gaming page
  packages/client/src/configs/Game.type.ts
  packages/client/src/molecules/GameSecton/GameResultMadal.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/organisms/GamePlaySection/GmaePlayTheme.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/pages/GameRoutePage.tsx
  packages/client/src/socket/event.ts
  packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
  packages/client/src/types/Game.type.ts
Labels: enhancement, front-end

#265 🐛 fix(server/game): start event를 참가자 전원에게 받고, 참가자가 맞는지 검증 (#260)
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
Labels: enhancement, back-end

#264 Feat/226/connect game socket
  node_modules/.yarn-integrity
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/index.tsx
  packages/client/src/molecules/GameSecton/GameOption.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/pages/GameRoutePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/game.recoil.ts
  packages/client/src/socket/event.ts
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/types/Game.type.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.service.ts
  yarn.lock
Labels: enhancement, front-end

#268 🐛 fix(server/connection): 연결관련 에러 처리 및 프론트엔드 요구사항 반영
  packages/server/src/users/dto/connect-user.dto.ts
  packages/server/src/users/users.service.ts
Labels: bug, back-end

#270 ✨ feat(server/chat): post channel image (#261)
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/users/users.entity.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#275 ✨ feat(client): create change room image 채팅방 이미지 변경
  packages/client/src/atoms/profile/ChatRoomImageProfile.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
Labels: enhancement, front-end

#276 🐛 fix(server/game): modified game logic (#274)
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.service.ts
Labels: back-end

#279 ✨ feat(server): TypeOrm 에러 핸들링 및 ExceptionFilter 추가
  packages/server/src/app.filter.ts
  packages/server/src/main.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#285 ✨ feat(server/chat): room password encryption (#180)
  package-lock.json
  packages/server/package.json
  packages/server/src/auth/auth.controller.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/game/game.service.ts
  yarn.lock
Labels: back-end

#286 🐛 fix(server/auth): db에 없는 유저가 로그인했을 때 404 error 해결 (#284)
  packages/server/src/auth/auth.service.ts
Labels: back-end

#290 🐛 fix(server): bctypt misspell (#288)
  package-lock.json
  package.json
  packages/server/src/chats/rooms.service.ts
  yarn.lock
Labels: back-end

#287 ✨ feat(server/game): get rank and game api & watch a game socket (#280)
  packages/server/init/init.sql
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#294 ✨ feat(server/auth): logout api & protect invalid access
  packages/server/src/auth/auth.controller.ts
  packages/server/src/auth/auth.module.ts
  packages/server/src/auth/auth.service.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.entity.ts
  packages/server/src/chats/rooms.module.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#297 Feat/267/invite game
  .gitignore
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/icon/CustomIconButtion.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/GameSecton/GameOption.tsx
  packages/client/src/organisms/Massage/InviteMessageList.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/pages/ProfilePage.tsx
  packages/client/src/recoil/common.recoil.ts
  packages/client/src/recoil/game.recoil.ts
  packages/client/src/socket/event.ts
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
  packages/client/src/types/Message.type.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/users/users.service.ts
  yarn-error.log
Labels: enhancement, front-end

#299 ✨ feat(server): add and fix returns on socket (#298)
  packages/server/src/game/game.service.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#301 🐛 fix(server/game): 공이 벽에 충돌하기 전 죽는 이슈 수정 (#274)
  node_modules/.yarn-integrity
  package-lock.json
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.service.ts
  yarn.lock
Labels: back-end

#303 🐛 fix(server/auth): unset AuthGuard in logout API (#302)
  packages/server/src/auth/auth.controller.ts
Labels: bug, back-end

#305 🐛 fix(server): fix saving game result & fix getRoomInfo bug (#304)
  packages/server/src/chats/rooms.service.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/users.entity.ts
Labels: back-end

#306 Feat/300/create game observer mode
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/atoms/text/MatchType.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/organisms/OrganismsStyles/ProfileOrganismsCss.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/pages/GameRoutePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/chat.recoil.ts
  packages/client/src/recoil/game.recoil.ts
  packages/client/src/socket/event.ts
  packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
  packages/client/src/types/Game.type.ts
  packages/server/src/game/game.service.ts
Labels: enhancement, front-end
