Repository Dream-Transcendence/ft_transcendence, pull requests merged in 2022-11, with the labels that each got.

#310 🐛 fix(server): change position of throwing User notfound exception (#…
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#311 🐛 fix(server/game): resolve Problems that do not end due to abstention (#307)
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
Labels: back-end

#313 🐛 fix(server/game): 매칭 중 game namespace에서 disconnect됐을 때 큐에서 삭제 (#312)
  packages/server/src/game/game.gateway.ts
  packages/server/src/game/game.service.ts
Labels: back-end

#316 Feat/267/invite game
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/icon/CustomIconButtion.tsx
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/input/SearchBox.tsx
  packages/client/src/atoms/text/ProfileUserStatLadder.tsx
  packages/client/src/atoms/text/ProfileUserStatLose.tsx
  packages/client/src/atoms/text/ProfileUserStatWin.tsx
  packages/client/src/configs/Game.type.ts
  packages/client/src/configs/userType.ts
  packages/client/src/hooks/useSearch.ts
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/GameSecton/GameOption.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/molecules/ProfileSection/UserProfileBox.tsx
  packages/client/src/organisms/GameCreateSection/GameOption.tsx
  packages/client/src/organisms/Massage/InviteMessageList.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/GameCreatePage.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/GameRoutePage.tsx
  packages/client/src/pages/PageStyles/ProfilePageCss.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/recoil/game.recoil.ts
  packages/client/src/socket/event.ts
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
  packages/client/src/texts/TextBox.tsx
  packages/client/src/types/Game.type.ts
  packages/client/src/types/Profile.type.ts
  packages/server/src/game/game.service.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.service.ts
Labels: enhancement, front-end

#319 🐛 fix(server/user): response empty array when search with empty strin…
  packages/server/src/users/users.service.ts
Labels: back-end

#322 🐛 fix(server/user): change GameRecordDto and its response order (#321)
  packages/server/src/game/game.dto.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#324 🐛 fix(server): 다른 방에 들어가있어도 소켓이 받아지는 오류 & 게임 시작 전 나갈 때 생기는 에러 수정
  packages/server/init/init.sql
  packages/server/src/chats/rooms.service.ts
  packages/server/src/game/game.service.ts
Labels: back-end

#328 Fix/315/fix chat and profile component 모의 평가를 통해 발견된 에러들을 수정하였습니다.
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/list/styles/ListStylesCSS.tsx
  packages/client/src/atoms/profile/ChatRoomImageProfile.tsx
  packages/client/src/atoms/textPrompt/MessageBox.tsx
  packages/client/src/molecules/ChatSection/ChatInput.tsx
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/pages/ProfilePage.tsx
  packages/client/src/pages/SecondOauthPage.tsx
  packages/client/src/recoil/chat.recoil.ts
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
Labels: enhancement, front-end

#330 🐛 fix(server): init sql double quotes to single
  packages/server/init/init.sql
Labels: bug, back-end

#332 Feat/331/fix change nickname
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
Labels: enhancement, front-end

#334 🐛 fix(server): filter blocked user messages in channel (#333)
  packages/server/src/chats/rooms.service.ts
Labels: back-end

#335 ✨ feat(server/user): add cancleInivte socket (#325)
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/user.gateway.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#338 ✨ feat(server/game): add live-games get api (#326)
  packages/server/src/game/game.controller.ts
  packages/server/src/game/game.service.ts
Labels: back-end

#339 Feat/326/game observe page 게임 관전 페이지 생성
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/hooks/useSearch.ts
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/Observe/LiveObserveElement.tsx
  packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/pages/LiveObservePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
Labels: enhancement, front-end

#345 🐛 fix(server/user): changeUserStatus when cancelInvite called (#342)
  packages/server/src/users/users.service.ts
Labels: back-end

#351 🐛 fix(server/user): not to friend request each others (#350)
  packages/server/src/users/users.service.ts
Labels: bug, back-end

#356 🐛 fix(server/user): 404 Exception to Object which has boolean isFrien…
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#358 🐛 fix(server/rooms): 메세지가 없고 마지막 유저가 방을 나갔을 때 터지는 이슈 해결 (#357)
  packages/server/src/chats/rooms.service.ts
Labels: back-end

#359 🐛 fix(server/user): getFriend to checkFriend with DTO (#353)
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#361 ✨ feat(server/game): add api check game exist (#354)
  packages/server/src/game/game.controller.ts
  packages/server/src/game/game.dto.ts
  packages/server/src/game/game.service.ts
Labels: back-end

#362 🐛 fix(server/game): readyMap의 value를 초기화 (close #360)
  packages/server/src/game/game.service.ts
Labels: back-end

#363 🐛 fix(server/user): change WsException body (#355)
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.service.ts
Labels: back-end

#364 Fix/315/delete_console
  packages/client/src/atoms/SpeedDial/SpeedDial.tsx
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/block/NicknameConfirmButton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageComponentButton.tsx
  packages/client/src/atoms/button/switch/SecondAuth.tsx
  packages/client/src/atoms/input/AutoCompleteSerchBox.tsx
  packages/client/src/atoms/input/ProfileNickname.tsx
  packages/client/src/atoms/profile/ChatRoomImageProfile.tsx
  packages/client/src/atoms/text/NicknameInitTextField.tsx
  packages/client/src/hooks/useSearch.ts
  packages/client/src/molecules/ChatSection/InfoBoxDMFunction.tsx
  packages/client/src/molecules/ChatSection/InfoBoxRoomFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/molecules/Observe/LiveObserveElement.tsx
  packages/client/src/organisms/ChatMainSection/ChatLogList.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/EnteredChatRoomInfo.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedChatRoomList.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/organisms/Massage/InviteMessageList.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfilePersonal/ProfilePersonal.tsx
  packages/client/src/organisms/ProfileUserInfo/OtherInfo.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/pages/GameLoadingPage.tsx
  packages/client/src/pages/GameRoutePage.tsx
  packages/client/src/pages/LandingPage.tsx
  packages/client/src/pages/LiveObservePage.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/pages/PingpongRoutePage.tsx
  packages/client/src/pages/SecondOauthPage.tsx
  packages/client/src/recoil/chat.recoil.ts
  packages/client/src/socket/useSocket.tsx
  packages/client/src/template/ChatMainSection/EnteredChatRoomTemplate.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/types/Message.type.ts
  packages/server/src/users/dto/user.dto.ts
  yarn-error.log
  yarn.lock
Labels: enhancement, front-end

#365 🐛 fix(client): fix nickname layout and fix error
  docker-compose.yml
  packages/client/src/organisms/NicknameInit/NicknameInit.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/template/ChatMainSection/ChatRoomListTemplate.tsx
Labels: bug, front-end
