Repository Dream-Transcendence/ft_transcendence, pull requests merged in 2022-09, with the labels that each got.

#47 📈 perf(client): devide search bar from Navbar
  packages/client/public/index.html
  packages/client/src/App.tsx
  packages/client/src/components/bar/NavigationBar.tsx
  packages/client/src/components/button/icon/LogoutButton.tsx
  packages/client/src/components/input/SearchBox.tsx
  packages/client/src/pages/ChatroomPage.tsx
  packages/client/src/pages/ProfilePage.tsx
Labels: front-end

#48 feat(client): 채팅페이지의 기본 레이아웃 구성 및 간단한 하위 컴포넌트 구현
  node_modules/.yarn-integrity
  packages/client/src/App.tsx
  packages/client/src/components/bar/NavigationBar.tsx
  packages/client/src/components/button/icon/ChatRoomOutIconButton.tsx
  packages/client/src/components/button/icon/ChatSendIconButton.tsx
  packages/client/src/components/input/SearchBox.tsx
  packages/client/src/components/textPrompt/ChatProfileNText.tsx
  packages/client/src/modules/ChatSection/SectionChatInput.tsx
  packages/client/src/modules/ChatSection/SectionChatLogList.tsx
  packages/client/src/modules/ChatSection/SectionChatParticipants.tsx
  packages/client/src/modules/ChatSection/SectionRoomInfo.tsx
  packages/client/src/modules/ChatSidebar/AsideCreateChatRoom.tsx
  packages/client/src/modules/ChatSidebar/AsideCurrentChatRoom.tsx
  packages/client/src/modules/ChatSidebar/AsideSearchBox.tsx
  packages/client/src/modules/ChatSidebar/AsidefriendList.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipants.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/ChatroomPage.tsx
  packages/client/src/template/ChatRoomTemplate.tsx
  packages/client/src/template/ChatSidebarTemplate.tsx
Labels: bug, enhancement, front-end, design

#61 Client/profile layout
  node_modules/.yarn-integrity
  packages/client/package.json
  packages/client/public/index.html
  packages/client/src/App.tsx
  packages/client/src/assets/songprofile.png
  packages/client/src/components/avatar/AvartarWithCircle.tsx
  packages/client/src/components/avatar/NavProfile.tsx
  packages/client/src/components/avatar/ProcileImage.tsx
  packages/client/src/components/avatar/ProfileBoxNickname.tsx
  packages/client/src/components/bar/NavigationBar.tsx
  packages/client/src/components/button/block/NicknameConfirmButton.tsx
  packages/client/src/components/list/ListGenerate.tsx
  packages/client/src/components/text/NicknameInitTextField.tsx
  packages/client/src/components/text/ProfileNicname.tsx
  packages/client/src/components/text/ProfileUserStatLose.tsx
  packages/client/src/components/text/ProfileUserStatWin.tsx
  packages/client/src/modules/ProfileSection/StatResult.tsx
  packages/client/src/modules/ProfileSection/UserProfileBox.tsx
  packages/client/src/organisms/NicknameInit/NicknameInit.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/pages/NicknamePage.tsx
  packages/client/src/pages/ProfilePage.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
  yarn.lock
Labels: front-end, design

#64 ✨ feat(client): create avatar, profile component ("feat #62")
  packages/client/src/atoms/NavProfile.tsx
  packages/client/src/atoms/ProfileAvatar.tsx
  packages/client/src/atoms/ProfileBoxNickname.tsx
  packages/client/src/atoms/ProfileImage.tsx
  packages/client/src/components/avatar/NavProfile.tsx
  packages/client/src/components/bar/NavigationBar.tsx
  packages/client/src/components/text/GamePlayer.tsx
  packages/client/src/components/text/MatchType.tsx
  packages/client/src/components/text/ProfileUserStatLadder.tsx
  packages/client/src/modules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/modules/ProfileSection/UserProfileBox.tsx
  packages/client/src/modules/ProfileSection/UserProfileBoxWithCircle.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
Labels: enhancement, front-end, design

#66 ✨ fix(client): create avatar, profile component
  packages/client/src/components/button/switch/SecondAuth.tsx
  packages/client/src/components/list/ListGenerate.tsx
  packages/client/src/components/text/ProfileNicname.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserInfo/UserInfo.tsx
Labels: enhancement, front-end, design

#74 ✨ feat(client): game loding page 구현 ("feat #73")
  packages/client/src/App.tsx
  packages/client/src/atoms/TextBox.tsx
  packages/client/src/components/button/block/ButtonCompenent.tsx
  packages/client/src/modules/ProfileSection/ProfileChatRoomBox.tsx
  packages/client/src/modules/ProfileSection/UserProfileBox.tsx
  packages/client/src/organisms/GameCreateSection/GameMap.tsx
  packages/client/src/pages/GameLodingPage.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
Labels: enhancement, front-end, design

#79 ✨ feat(client): add GameResult Modal ("feat #78")
  packages/client/src/App.tsx
  packages/client/src/atoms/ProfileAvatar.tsx
  packages/client/src/atoms/TextBox.tsx
  packages/client/src/modules/GameSecton/GameResultMadal.tsx
  packages/client/src/modules/GameSecton/GameScore.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/pages/GameCreatePage.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/template/GameCreateSection/GamePlayTemplate.tsx
Labels: enhancement, front-end, design

#85 ✨ feat(common): add eslint for useCallback
  .eslintrc.js
  node_modules/.yarn-integrity
  package-lock.json
  package.json
  packages/client/src/components/list/ListGenerate.tsx
  packages/client/src/modules/ChatSidebar/SearchBox.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/template/ChatMainSection/ChatSidebarTemplate.tsx
  yarn.lock
Labels: enhancement, front-end

#89 feat(common): setting for recoil
  .eslintrc.js
  package.json
  packages/client/package.json
  packages/client/src/App.tsx
  yarn.lock
Labels: enhancement, front-end

#95 🐛 fix(client): atomic pattern 으로 디렉토리 이름 수정
  packages/client/src/atoms/profile/ProfileImage.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomInvite.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomName.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomPassword.tsx
  packages/client/src/molecules/ChatPopUp/SetChatRoomType.tsx
  packages/client/src/molecules/ChatSection/ChatInput.tsx
  packages/client/src/molecules/ChatSection/RoomElementImage.tsx
  packages/client/src/molecules/ChatSection/RoomElementNumOfPeople.tsx
  packages/client/src/molecules/ChatSection/RoomElementTitle.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxFunction.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxName.tsx
  packages/client/src/molecules/ChatSection/RoomInfoBoxPassword.tsx
  packages/client/src/molecules/ChatSidebar/CreateChatRoom.tsx
  packages/client/src/molecules/ChatSidebar/SearchBox.tsx
  packages/client/src/molecules/CommonSection/ReceiveMessageAlert.tsx
  packages/client/src/molecules/CommonSection/SendMessageAlert.tsx
  packages/client/src/molecules/GameSecton/GameOption.tsx
  packages/client/src/molecules/GameSecton/GameResultMadal.tsx
  packages/client/src/molecules/GameSecton/GameScore.tsx
  packages/client/src/molecules/ProfileSection/OneMatchHistory.tsx
  packages/client/src/molecules/ProfileSection/ProfileChatRoomBox.tsx
  packages/client/src/molecules/ProfileSection/StatResult.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/molecules/ProfileSection/UserInviteBox.tsx
  packages/client/src/molecules/ProfileSection/UserProfileBox.tsx
  packages/client/src/molecules/ProfileSection/UserProfileBoxWithCircle.tsx
  packages/client/src/organisms/ChatMainSection/ChatParticipantsList.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/Chatting.tsx
  packages/client/src/organisms/ChatMainSection/EnteredRoomInfo.tsx
  packages/client/src/organisms/ChatPopUp/SettingRoomConfig.tsx
  packages/client/src/organisms/ChatSidebar/JoinedChatRoomList.tsx
  packages/client/src/organisms/ChatSidebar/JoinedDMList.tsx
  packages/client/src/organisms/GameCreateSection/GameOption.tsx
  packages/client/src/organisms/GamePlaySection/GamePlayWindow.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/organisms/ProfileMatchHistory/MatchHistory.tsx
  packages/client/src/organisms/ProfileUserStat/UserStat.tsx
  packages/client/src/template/ChatMainSection/ChatSidebarTemplate.tsx
  packages/client/src/template/ProfileSection/ProfileTemplate.tsx
Labels: front-end

#93 API 명세 표기를 위한 Swagger 작성
  node_modules/.yarn-integrity
  packages/server/.gitignore
  packages/server/nest-cli.json
  packages/server/package.json
  packages/server/src/app.module.ts
  packages/server/src/channel-participants/channel-participants.controller.ts
  packages/server/src/channel-participants/channel-participants.entity.ts
  packages/server/src/channel-participants/channel-participants.module.ts
  packages/server/src/channel-participants/dto/channel-participants.dto.ts
  packages/server/src/config/db/typeorm-ex.decorator.ts
  packages/server/src/config/db/typeorm-ex.module.ts
  packages/server/src/database/database.module.ts
  packages/server/src/database/database.providers.ts
  packages/server/src/game/game.controller.ts
  packages/server/src/game/game.module.ts
  packages/server/src/main.ts
  packages/server/src/rooms/dto/rooms.dto.ts
  packages/server/src/rooms/rooms.controller.ts
  packages/server/src/rooms/rooms.entity.ts
  packages/server/src/rooms/rooms.module.ts
  packages/server/src/rooms/rooms.repository.ts
  packages/server/src/rooms/rooms.service.ts
  packages/server/src/users/dto/auth-user.dto.ts
  packages/server/src/users/dto/create-user.dto.ts
  packages/server/src/users/dto/patch-user.dto.ts
  packages/server/src/users/dto/user.dto.ts
  packages/server/src/users/users.controller.ts
  packages/server/src/users/users.entity.ts
  packages/server/src/users/users.module.ts
  packages/server/src/users/users.providers.ts
  packages/server/src/users/users.service.ts
  packages/server/tsconfig.build.json
  packages/server/tsconfig.json
  yarn.lock
Labels: back-end

#97 ♻️ refactor(client): navbar is changed to sub route ("close #96")
  node_modules/.yarn-integrity
  packages/client/src/App.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/GameCreatePage.tsx
  packages/client/src/pages/GamePlayPage.tsx
  packages/client/src/pages/PingpongLayout.tsx
  packages/client/src/pages/ProfilePage.tsx
Labels: front-end

#103 ✨ feat(client): make link page button
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/icon/ChatIconButton.tsx
  packages/client/src/atoms/button/icon/GameIconButton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageIconButton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageTextButton.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/types/Link.type.ts
Labels: front-end

#105 Feat/101/page link button(client) 채팅채널 페이지 구조 개선
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/block/ButtonCompenent.tsx
  packages/client/src/atoms/button/linkPage/HistoryBackTextButton.tsx
  packages/client/src/atoms/button/linkPage/LinkPageTextButton.tsx
  packages/client/src/atoms/button/text/TextButton.tsx
  packages/client/src/atoms/input/passwordBox.tsx
  packages/client/src/atoms/profile/ProfileAvatar.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomList.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/pages/GameLodingPage.tsx
  packages/client/src/pages/PingpongLayout.tsx
  packages/client/src/template/ChatMainSection/ChatRoomListTemplate.tsx
  packages/client/src/template/GameCreateSection/GameCreateTemplate.tsx
  packages/client/src/types/Link.type.ts
Labels: front-end

#108 feat(server): rooms, channelParticipants api 구현
  packages/server/src/app.module.ts
  packages/server/src/channel-participants/channel-participants.controller.ts
  packages/server/src/channel-participants/channel-participants.entity.ts
  packages/server/src/channel-participants/channel-participants.module.ts
  packages/server/src/channel-participants/dto/channel-participants.dto.ts
  packages/server/src/chats/dto/room.dto.ts
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.entity.ts
  packages/server/src/chats/rooms.module.ts
  packages/server/src/chats/rooms.providers.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/config/db/typeorm-ex.decorator.ts
  packages/server/src/config/db/typeorm-ex.module.ts
  packages/server/src/database/database.providers.ts
  packages/server/src/rooms/rooms.controller.ts
  packages/server/src/rooms/rooms.entity.ts
  packages/server/src/rooms/rooms.module.ts
  packages/server/src/rooms/rooms.repository.ts
  packages/server/src/rooms/rooms.service.ts
  packages/server/src/users/users.entity.ts
Labels: back-end

#107 ✨ feat(client): chatroom page내에 프로필 이동 버튼 link 구현 ("feat #102")
  packages/client/src/atoms/bar/NavigationBar.tsx
  packages/client/src/atoms/button/block/NicknameConfirmButton.tsx
  packages/client/src/configs/Link.url.ts
  packages/client/src/molecules/ChatSection/RoomInfoBoxFunction.tsx
  packages/client/src/molecules/ProfileSection/UserChatParticipants.tsx
  packages/client/src/molecules/ProfileSection/UserProfileBox.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/NicknameInit/NicknameInit.tsx
  packages/client/src/organisms/ProfileFreindList/FreindList.tsx
  packages/client/src/pages/LandingPage.tsx
Labels: enhancement, front-end

#112 🐛 fix(server): addChannelParticipants 로직 수정 (#111)
  packages/server/src/chats/dto/room.dto.ts
  packages/server/src/chats/dto/rooms.dto.ts
  packages/server/src/chats/rooms.controller.ts
  packages/server/src/chats/rooms.entity.ts
  packages/server/src/chats/rooms.service.ts
  packages/server/src/database/database.providers.ts
Labels: back-end

#113 ✨ feat(client): change state to atom
  packages/client/src/organisms/ChatMainSection/ChatRoomElement.tsx
  packages/client/src/organisms/ChatMainSection/ChatRoomList.tsx
  packages/client/src/pages/ChatChannelPage.tsx
  packages/client/src/template/ChatMainSection/ChatRoomListTemplate.tsx
  packages/client/src/texts/TextBox.tsx
Labels: enhancement, front-end
